version: '3'
services:
  nextjs:
    container_name: nextjs
    image: ${DOCKER_REGISTRY_SERVER}/${DOCKER_IMAGE_NAME}_nextjs:${DOCKER_IMAGE_TAG}
  nginx:
    container_name: nginx
    image: ${DOCKER_REGISTRY_SERVER}/${DOCKER_IMAGE_NAME}_nginx:${DOCKER_IMAGE_TAG}
    ports:
      - 8080:8080
